### ISSUE TITLE
[JOSS Review] Code quality comment

### ISSUE THREAD

**Issue by natir** [esteinig/nanoq#18]
This relates to my JOSS review openjournals/joss-reviews#2991

First thanks for your work on this tools and publications

Some comments about code quality:

- [x] Add Continuous Integration could help to improve and keep an high quality of code. You can take inspiration from [rust-bio github action](https://github.com/rust-bio/rust-bio/blob/master/.github/workflows/rust.yml) don't hesitate to include test coverage
- [x] I notice some classic rust style error in code use [clippy](https://github.com/rust-lang/rust-clippy) could help to detect and fix them
- [x] To facilitate contribution could you split `main.rs` in some submodule and add documentation

**Comment by esteinig** [comment]
Again, some comments before working on the `joss` branch:

1. Yep can implement some CI (I think) 
2. Oh cool, thanks for the tip, will lint the code
3. Yep will do!

**Comment by esteinig** [comment]
In regards to your points:
- [x] added continuous integration actions for push, pull requests, and release; added test coverage 
- [x] `clippy` compliant code - it was a bit of a mess before, but hopefully much better now
- [x] code split into submodules and documentation added throughout
