### ISSUE TITLE
[JOSS Review] Other comments

### ISSUE THREAD

**Issue by natir** [esteinig/nanoq#19]
This relates to my JOSS review openjournals/joss-reviews#2991

First thanks for your work on this tools and publications

I put here the comments that I could not group with others:

- [x] Link to nanopore documentation about quality score require login to nanopore website, can you provide another link ?
- [x] Did you plan to replace your own conda by a bioconda recipe ? (I could do it for you)

**Comment by esteinig** [comment]
@natir thanks very much for your comments and improvements - in the other threads as well. I will work on this tonight :)

**Comment by esteinig** [comment]
1. Yes, good point! There was a discussion on this during development of `Nanostat` which might be relevant and not behind a community wall. Please let me know if this is appropriate: https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/ 

2. Yes, absolutely. I will give it a shot but have had Michael's excellent help last time. I might have to come back to your generous offer

**Comment by natir** [comment]
1. it's ok
2. If you want you can take inspiration from my package [yacrd](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/yacrd) or [fpa](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/fpa) don't hesitate to tag me in your bioconda pull request, I would review it with pleasure.

**Comment by esteinig** [comment]
thanks heaps, appreciate the help!
