### ISSUE TITLE
FASTA statistics is not handled properly

### ISSUE THREAD

**Issue by cgjosephlee** [esteinig/nanoq#21]
When filtering FASTA or just generating stats I met
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', src/main.rs:678:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
But the output FASTA is correct. Should be some errors during generating statistics.

Btw, if we can optionally ignore quality scores, some operations on FASTQ will be much much faster. 
eg. I only want to filter a FASTQ by read length.

**Comment by esteinig** [comment]
Thanks so much for stress testing Joseph, much appreciated! Added to the list: bug fix as well as optional q-scores, will also test the option in the benchmarks.

**Comment by esteinig** [comment]
@cgjosephlee changes implemented (sorry for delay):

* main branch now has a stable release fixing the stats bug
* `-f / --fast` mode which ignores quality scores - huge speedup as suggested

**Comment by esteinig** [comment]
will close for now but feel free to reopen if you run into any issues

thanks for the report and suggestion!
