### ISSUE TITLE
Basic summary statistics

### ISSUE THREAD

**Issue by esteinig** [esteinig/nanoq#3]
Besides filtering by read length and average quality `nanoq` now outputs some summary statistics similar to [`NanoStat`](https://github.com/wdekoster/NanoStat) as simple numerics to `STDERR`:

```bash
29082396 5000 62483 120 5816 2898 11.87 12.02
```

corresponding to: 

```bash
bp_total num_reads longest_reads shortest_read mean_length median_length mean_q median_q
```

**Comment by esteinig** [comment]
Run the command line interface with default flags (`--length 0`, `--quality 0`) to skip filters and to compute only statistics:

```
nanoq -f test.fq
```

**Comment by mbhall88** [comment]
It would be nice to add an option `-H,--header` maybe that outputs the corresponding headers for the stats? I regularly have to come back to the webpage to look up which is which. Or maybe you could even add it in the long help menu for the stats option?

**Comment by esteinig** [comment]
Good point! I'll fix something up over the weekend. Do you think hardcoding headers into the output would be too much? Or more convenient?

**Comment by mbhall88** [comment]
Up to you mate. Leave them out by default I reckon, that way there are no compatibility problems. Then as I said, add an option to output them?

**Comment by esteinig** [comment]
Sounds like a good solution, thanks for your input!
