### ISSUE TITLE
How to use multithreading

### ISSUE THREAD

**Issue by Tang-pro** [esteinig/nanoq#47]
@Euglenoid @esteinig 
Hi, 
Can you specify the number of threads? Because this is running a bit slow.

**Comment by esteinig** [comment]
`Nanoq` is a single pass read iteration and as such does not implement multiple threads like most other tools in this space e.g. `seqtk` (https://github.com/lh3/seqtk). 

I assume your read file is large. If you don't need to compute average quality scores you can switch those off with the `--fast` option which should speed up iteration significantly.
