### ISSUE TITLE
stdin / stdout

### ISSUE THREAD

**Issue by esteinig** [esteinig/nanoq#7]
Implement reading and writing streams

**Comment by esteinig** [comment]
@mbhall88 how would i go about implementing `fastq::Reader::from_file(filename)` with `stdin` - is there an idiomatic way in `rust-bio`?

**Comment by esteinig** [comment]
Oh man, it's literally in the first header comments of the code:

```rust
let reader = fastq::Reader::new(io::stdin());
```

**Comment by esteinig** [comment]
Hmmm but how to implement so it doesn't complain about different types assigned to reader in the match arms:

```rust
let reader = match cli.value_of("fastq") {
        Some(filename) => fastq::Reader::from_file(filename).expect("Error"),
        None | Some("-") => fastq::Reader::new(io::stdin())
    };
```

i.e. `expected struct std::fs::File, found struct std::io::Stdin`

**Comment by mbhall88** [comment]
You need to indicate that your `reader` implements the trait `Read`.

```rust
use std::env;
use std::fs;
use std::io::{self, BufReader, Read};
use bio::io::fastq;

fn main() {
    let input = env::args().nth(1);
    let handle: Box<dyn Read> = match input {
        Some(filename) if filename != "-" => Box::new(fs::File::open(filename).unwrap()),
        _ => Box::new(BufReader::new(io::stdin())),
    };

    let reader = fastq::Reader::new(handle);

    for record in reader.records() {
        match record {
            Ok(r) => println!("{:?}", r),
            _ => println!("Bad record")
        }
    }
}
```

This is adapted as a combination of [this SO answer][so] and my own [`Fastx` implementation][rasusa] in `rasusa`.

[so]: https://stackoverflow.com/a/49964042/5299417
[rasusa]: https://github.com/mbhall88/rasusa/blob/9f14d9db936ccfd6e97f43f1b1724f5bd15de065/src/fastx.rs#L177-L193

**Comment by esteinig** [comment]
Right ok and the `Box` has to do with how to allocate the type to memory? Why is that necessary? Thanks so much for taking the time!

**Comment by esteinig** [comment]
I changed this now to

```rust
let input_handle: Box<dyn Read> = match cli.value_of("fastq") {
        Some(filename) => Box::new(fs::File::open(filename).unwrap()),
        None =>  Box::new(BufReader::new(io::stdin()))
    };
```

Very nice!

**Comment by mbhall88** [comment]
`Box` is a smart pointer. Basically, Rust wants to know how much memory to allocate (and where to allocate it stack/heap) during compilation (hence its memory safety). Because we are saying the return value just needs to implement the trait `Read`, the object being returned could theoretically be of any size. Therefore it is going to need to be allocated memory from the heap. From the always-wonderful [documentation in the rust book about `Box`](https://doc.rust-lang.org/book/ch15-01-box.html).
> [When to use a `Box<T>`] When you want to own a value and you care only that it’s a type that implements a particular trait rather than being of a specific type

*NB: It would be nice to allow for being verbose about stdin with `"-"` in your implementation.*

**Comment by esteinig** [comment]
Dude that's a great explanation. I was trying to figure this out. I'll add the conditional to add the `"-"` back into it. Thanks heaps!
