### ISSUE TITLE
Distributions

### ISSUE THREAD

**Issue by esteinig** [esteinig/nanoq#9]
Add distribution for Docker, Singularity, Conda and Cargo.

**Comment by esteinig** [comment]
Need smaller binary in `alpine` container if possible.

**Comment by cgjosephlee** [comment]
Hi Eike,
Is it possible to have a static binary distribution within a single executable?

**Comment by esteinig** [comment]
Hey, not quite sure if I understand correctly, but do you mean distribution of compiled binaries for Linux / OS / Windows with the releases? Very happy to provide them.

Please let me know if that's not what you meant.

**Comment by cgjosephlee** [comment]
Exactly! A portable distribution would be nice for easy deployment.

**Comment by esteinig** [comment]
Yep, of course, thanks for reminding me to put those into the releases. I'm working on the codebase tonight, and will upload them for the last release. I think the next release will have CI as suggested by the JOSS reviewers to automatically create them. Any specific distribution you are after?

**Comment by cgjosephlee** [comment]
I guess simplify a linux x86 version can fit ~90% needs in bioinfomatics.

**Comment by esteinig** [comment]
Indeed, Linux x86 it is then, should be simple with Rust, and will provide other platforms as well. Thanks for raising this!

**Comment by cgjosephlee** [comment]
Glad to heard that!

**Comment by esteinig** [comment]
Apologies for the delay (finishing my PhD thesis at the moment) - they should be online after the weekend!

**Comment by esteinig** [comment]
Well that took a bit longer ... but they are online now @cgjosephlee together with a complete rewrite of the program :tada:

**Comment by cgjosephlee** [comment]
Awesome work!
